name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.16"]
        os: [ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Run provider tests
        run: cd mikrotik && go test -v ./...
        env:
          MIKROTIK_HOST: 127.0.0.1:8728
          MIKROTIK_USER: admin
          MIKROTIK_PASSWORD: ''
          TF_ACC: 1

    services:
      routeros:
        image: evilfreelancer/docker-routeros:6.48.3
        ports:
          - 8728:8728
        volumes:
          - /dev/net/tun:/dev/net/tun
        options: >-
          --cap-add=NET_ADMIN
